name: stock-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter
  - notebook
  - ipykernel
  - pip:
    - xgboost>=1.5.0
    - lightgbm>=3.3.0
    - catboost>=1.0.0
    - yfinance>=0.1.70
    - tushare>=1.2.89
    - TA-Lib>=0.4.24
    - optuna>=3.0.0
    - plotly>=5.0.0
    - joblib>=1.1.0
    - python-dotenv>=0.19.0
    - PyYAML>=6.0
    - requests>=2.26.0
    - beautifulsoup4>=4.10.0
    - sqlalchemy>=1.4.0
    - psycopg2-binary>=2.9.0
    - pymongo>=4.0.0
    - redis>=4.0.0
    - celery>=5.2.0
    - fastapi>=0.70.0
    - uvicorn>=0.15.0
    - pydantic>=1.8.0
    - pytest>=6.0.0
    - pytest-cov>=3.0.0
    - black>=22.0.0
    - flake8>=4.0.0
    - isort>=5.10.0
    - mypy>=0.910 